server:
  port: ${SERVER_PORT:6070}
  servlet:
    context-path: ${CONTEXT_PATH:/ms-store}

spring:
  application:
    name: ms-shop

  datasource:
    url: jdbc:mysql://${HOST}/${NAMEBD}
    username: ${USER}
    password: ${PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  security:
    jwt:
      secret-key: ${JWT_SECRET}


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha
    docExpansion: none
    displayRequestDuration: true
    filter: true
  api-docs:
    enabled: true
    path: /api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

auth:
  properties:
    excludedUrls:
      - "/swagger-ui.html"
      - "/swagger-ui/**"
      - "/api-docs"
      - "/api-docs/**"
      - "/v3/api-docs"
      - "/v3/api-docs/**"
      - "/api/v1/public/**"
      - "/api/v1/payments/stripe/webhook"

management:
  endpoints:
    web:
      exposure:
        include: "*"

client:
  server:
    mail: "http://localhost:6001/ms-mail"

ms-auth:
  base-url: "http://localhost:6001/ms-mail"

app:
  stripe:
    secret-key: ${STRIPE_SECRET_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}
